# -*- coding: utf-8 -*-
"""Listas 05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cYyQHisbLGJDJgpQdc9_tRBiyoS3rQea

# Algumas Funções Básicas de Lista

## Tamanho da Lista

tamanho = len(lista)
"""

produtos = ['apple tv', 'mac', 'iphone x',
            'IPad', 'apple watch', 'mac book', 'airpods']

tamanho = len(produtos)
print('temos {} produtos'.format(tamanho))

"""- Quantos produtos temos a venda?"""


"""## Maior e Menor Valor

maior = max(lista)

menor = min(lista)
"""

vendas = [1000, 1500, 15000, 270, 900, 100, 1200]
mais_vendas = max(vendas)
menos_vendas = min(vendas)
print('o produto mais vendido teve {} vendas e o menos vendido teve {} vendas'.format(
    mais_vendas, menos_vendas))

"""- Qual o item mais vendido?
- Qual o item menos vendido?
"""
imais = vendas.index(mais_vendas)
imenos = vendas.index(menos_vendas)
produto_mais_vendido = produtos[imais]
produto_menos_vendido = produtos[imenos]
print('Produto mais vendido foi {} e o menos vendido foi {}'.format(
    produto_mais_vendido, produto_menos_vendido))
