# -*- coding: utf-8 -*-
"""Operações com String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T8Wj4GgryCVh_1ujmjNCLlJFQDkmdq7C

# Operações com String

str -> transforma número em string<br>
in -> verifica se um texto está contido dentro do outro<br>
operador + -> concatenar string<br>
format e {} -> substitui valores<br>
%s -> substitui textos<br>
%d -> substitui números decimais<br>

Vamos deixar uma cartilha para download
"""

faturamento = 1000
custo = 500
lucro = faturamento - custo

"""Uso do str() e do concatenar com +"""

print('O faturamento da loja foi de: ' + str(faturamento) +
      ' o custo foi de: ' + str(custo) + ' o locro foi de: ' + str(lucro))

"""Uso do Format"""

print('O faturamento da loja foi de: {} o custo foi de: {} o locro foi de: {}'.format(
    faturamento, custo, lucro))
print('O faturamento da loja foi de: {0} o custo foi de: {1} o locro foi de: {2} faturamento é {0}'.format(
    faturamento, custo, lucro))

"""Uso do %s e %d"""

print('O faturamento da loja foi de: %d o custo foi de: %d o locro foi de: %d' %
      (faturamento, custo, lucro))

"""Uso do in (mais exercícios práticos nas próximas aulas)"""

print('@' in 'lira@gmail.com')
print('@' in 'lira.gmail.com')
